apiVersion: v1
kind: Service
metadata:
  name: business-service
spec:
  selector:
    app: business-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: business-service
  template:
    metadata:
      labels:
        app: business-service
    spec:
      containers:
        - name: business-service
          image: niminonline/salesyncer:business-service-v1
          ports:
            - containerPort: 3003
          resources:
            limits:
              cpu: "500m"  # 0.5 cores
              memory: "512Mi"
            requests:
              cpu: "100m"  # 0.1 cores
              memory: "256Mi"
          volumeMounts:
            - name: logs
              mountPath: /var/logs/salesyncer
      volumes:
        - name: logs
          emptyDir: {}