apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: niminonline/salesyncer:client-v1
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"  # 0.5 cores
              memory: "512Mi"
            requests:
              cpu: "100m"  # 0.1 cores
              memory: "256Mi"
