apiVersion: v1
kind: Service
metadata:
  name: office-service
spec:
  selector:
    app: office-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: office-service
  template:
    metadata:
      labels:
        app: office-service
    spec:
      containers:
        - name: office-service
          image: niminonline/salesyncer:office-service
          ports:
            - containerPort: 3002
          resources:
            limits:
              cpu: "500m"  # 0.5 cores
              memory: "512Mi"
            requests:
              cpu: "100m"  # 0.1 cores
              memory: "256Mi"
          volumeMounts:
            - name: logs
              mountPath: /var/logs/salesyncer
      volumes:
        - name: logs
          emptyDir: {}